[package]
name = "uefipxe-bootloader"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
uefi.workspace = true
uefi-raw.workspace = true
log.workspace = true
heapless.workspace = true
arrayvec.workspace = true
sha2.workspace = true
